### ISSUE TITLE
[Suggestion] Server restarting

### ISSUE THREAD

**Issue by alsoGAMER** [Aceheliflyer/papermc-docker#1]
Server restarting should be handled directly by docker, i think you can use the healthchecking feature to tell docker to restart the container if the status isn't healthy.

**Comment by AriRexouium** [comment]
Ideally I wanted the shutdown & restart command to work as intended. Restarting is identical to shutting down besides how it looks for a file named `start.sh` and runs the file if it exists. I don't really see a way that the server could communicate to Docker that it's requesting a restart since restarting the server would just stop the container.

**Comment by alsoGAMER** [comment]
> Restarting is identical to shutting down besides how it looks for a file named `start.sh` and runs the file if it exists. 

yeah i know that.

> I don't really see a way that the server could communicate to Docker that it's requesting a restart since restarting the server would just stop the container.

hm, that's true.. honestly i don't know either, but i guess that a quick read to the docker documentation could help
